name: CI

on:
 push:
  branches:
   - develop
   - master
  tags:
   - "!*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Version
      run: clang++ --version

    - name: Build
      run: clang++ -std=c++1y -Wall -Wextra -pedantic src/test.cpp && ./a.out

    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
       name: artifact
       path: a.out

