name: Release

on:
 create:
  branches:
   - "!*"
  tags:
   - "v*.*.*"

jobs:
 build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
       tag_name: ${{ github.ref }}
       release_name: ${{ github.ref }}
       draft: true
       prerelease: false
    
    - name: Build
      run: clang++ -std=c++1y -Wall -Wextra -pedantic src/test.cpp && ./a.out
    
    - name: Upload Release Asset
      uses: actions/upload-release-asset@master
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
       upload_url: ${{ steps.create_release.outputs.upload_url }}
       asset_path: a.out
       asset_name: a.out
       asset_content_type: application/octet-stream

