name: Release

on:
 create:
  tags:
  - v*.*.*

jobs:
 build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
       version: 1.12
      id: go

    - uses: actions/checkout@v1
    - name: Version
      run: clang++ --version

    - name: Build
      env:
       GO111MODULE: on
       GOPATH: /home/runner/work/
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
       export CREATE_EVENT_REF_TYPE=$(jq --raw-output .ref_type "$GITHUB_EVENT_PATH")
       export TAGNAME=$(jq --raw-output .ref "$GITHUB_EVENT_PATH")
       if [ "$CREATE_EVENT_REF_TYPE" != "tag" ]; then echo "ref_type is not a tag: ${CREATE_EVENT_REF_TYPE}" && exit 78; fi
       clang++ -std=c++1y -Wall -Wextra -pedantic src/test.cpp && ./a.out
       go get -u github.com/tcnksm/ghr
       $GOPATH/bin/ghr -n ${TAGNAME} -b "Release ${TAGNAME}" -draft ${TAGNAME} a.out

